[package]
name = "mdescriptor-studio"
version = "0.1.0"
description = "MDescriptor Studio - Materials Dataset & Descriptor Analysis Studio"
edition = "2021"
rust-version = "1.77"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde_json = "1"
sha2 = "0.10.9"

[profile.release]
strip = true
lto = true
codegen-units = 1
