"""Per-environment Jacobian rank diagnostics.

The paper-level feature of the diagnostics layer (review 2026-10-03, P0): a
whole-structure Jacobian almost always looks full rank because it has one block
row per atom, so completeness failures hide in per-atom blocks.  This module
differentiates every atom's descriptor row with respect to the positions of the
atoms inside its neighbor sphere, projects the three rotational zero modes out
of the displacement domain and reports the singular spectrum per environment:

    expected_rank  = 3 * n_neighbors - 3      (rotations are the only exact
                                               zero modes once the center is
                                               held fixed)
    observed_rank  = #{sigma > rank_tolerance * sigma_max}
    deficiency     = expected_rank - observed_rank

A deficiency means the descriptor cannot see some displacement direction inside
the neighbor sphere - the local degeneracy that "descriptor distance ~ 0 but
structures differ" is made of.  The rotational zero-mode residual is reported
alongside: a large value means the descriptor is not even rotation-invariant at
first order, which is a formal-correctness failure rather than incompleteness.

The Jacobian is central finite differences through the engine recompute
callable: one displaced copy per (atom, axis, sign), all atoms differentiated
per structure, so the cost is 6 * n_atoms small-structure evaluations per
selected frame regardless of how many central atoms are analyzed.
"""

from __future__ import annotations

from typing import Callable, Sequence

import numpy as np

from ...errors import ANALYSIS_INPUT_INVALID, AppError
from .geometry import DescriptorRecompute, replace_geometry


def _rotational_directions(deltas_from_center: np.ndarray) -> np.ndarray:
    """Domain directions (3, 3*n_neighbors) generated by infinitesimal rotations.

    Row axis e holds, for every (neighbor, coordinate) pair, the displacement
    d(e x r_ij)/dx_j[a] = (e x r_ij)[a] - rotating the whole neighbor sphere
    about the fixed center by a small angle moves neighbor j by e x r_ij.
    """
    axes = np.eye(3)
    rows = np.empty((3, deltas_from_center.size), dtype=np.float64)
    for e in range(3):
        generator = np.cross(axes[e], deltas_from_center)  # (n_neighbors, 3)
        rows[e] = generator.reshape(-1)
    return rows


def _analyze_environment(
    jacobian: np.ndarray,
    deltas_from_center: np.ndarray,
    rank_tolerance: float,
) -> dict:
    """SVD statistics for one central atom's Jacobian block.

    ``jacobian``: (3 * n_neighbors, n_features) with displacement rows;
    internally transposed to the (n_features, displacement) Jacobian so the
    generator directions act from the right.  ``deltas_from_center``:
    (n_neighbors, 3) minimum-image neighbor displacements.
    """
    n_displacements = jacobian.shape[0]
    if n_displacements == 0:
        return {
            "neighbor_count": 0,
            "expected_rank": 0,
            "observed_rank": 0,
            "rank_deficiency": 0,
            "sigma_max": 0.0,
            "sigma_min_significant": None,
            "condition_number": None,
            "rotational_residual": None,
        }
    jac = jacobian.T  # (n_features, 3 * n_neighbors)
    sigma_all = np.linalg.svd(jac, compute_uv=False)
    sigma_max = float(sigma_all[0]) if sigma_all.size else 0.0

    directions = _rotational_directions(deltas_from_center)
    # Degenerate configurations can zero out a generator (neighbors collinear
    # with a rotation axis): only non-trivial directions define the rotation
    # subspace, and projecting arbitrary orthonormal complements would remove
    # real rank.  The residual is likewise read over the kept directions only.
    norms = np.linalg.norm(directions, axis=1)
    keep = norms > 1e-12 * max(float(np.max(norms)), 1e-300)
    rotational_residual = None
    projected = jac
    if np.any(keep):
        kept = directions[keep]  # (n_kept, n_displacements)
        residuals = np.linalg.norm(jac @ kept.T, axis=0)  # feature-space image norms
        rotational_residual = float(np.max(residuals) / max(sigma_max, 1e-300))
        # Project the rotation subspace out of the displacement domain before
        # the rank readout; the residual above keeps the raw invariance check.
        orthonormal, _ = np.linalg.qr(kept.T)  # (n_displacements, n_kept)
        projected = jac - (jac @ orthonormal) @ orthonormal.T
    sigma = np.linalg.svd(projected, compute_uv=False)
    significant = sigma[sigma > rank_tolerance * max(float(sigma[0]), 1e-300)] if sigma.size else sigma
    observed_rank = int(significant.size)
    expected_rank = 3 * (n_displacements // 3) - 3
    sigma_min = float(significant[-1]) if observed_rank else None
    condition = float(sigma[0] / sigma[-1]) if sigma.size and sigma[-1] > 0 else None
    return {
        "neighbor_count": int(n_displacements // 3),
        "expected_rank": int(max(expected_rank, 0)),
        "observed_rank": observed_rank,
        "rank_deficiency": int(max(expected_rank, 0) - observed_rank),
        "sigma_max": sigma_max,
        "sigma_min_significant": sigma_min,
        "condition_number": condition,
        "rotational_residual": rotational_residual,
    }


def environment_jacobian(
    frames: Sequence,
    recompute: Callable[[Sequence], DescriptorRecompute],
    params: dict,
    progress: Callable[[float, str], None] | None = None,
) -> dict:
    """Rank the per-environment Jacobians of bounded, preselected structures.

    Requires atom-level recompute output.  ``params['cutoff']`` defines the
    neighbor sphere the expected-rank contract refers to; it should match the
    descriptor's own cutoff, and the summary reports how many neighbors the
    Jacobian actually sees so a cutoff mismatch is visible instead of being
    misread as incompleteness.
    """
    cutoff = params.get("cutoff")
    if cutoff is None:
        raise AppError(ANALYSIS_INPUT_INVALID, "environment jacobian requires a neighbor sphere cutoff in angstrom")
    cutoff = float(cutoff)
    if not np.isfinite(cutoff) or cutoff <= 0:
        raise AppError(ANALYSIS_INPUT_INVALID, "cutoff must be a positive number")
    try:
        displacement = float(params.get("displacement", 1e-3))
    except (TypeError, ValueError) as exc:
        raise AppError(ANALYSIS_INPUT_INVALID, "displacement must be a number") from exc
    if not np.isfinite(displacement) or not 1e-6 <= displacement <= 1e-1:
        raise AppError(ANALYSIS_INPUT_INVALID, "displacement must be between 1e-6 and 1e-1 angstrom")
    rank_tolerance = float(params.get("rank_tolerance", 1e-6))
    if not np.isfinite(rank_tolerance) or not 1e-12 < rank_tolerance < 1.0:
        raise AppError(ANALYSIS_INPUT_INVALID, "rank_tolerance must be in (1e-12, 1)")
    try:
        max_atoms = int(params.get("max_atoms", 32))
    except (TypeError, ValueError) as exc:
        raise AppError(ANALYSIS_INPUT_INVALID, "max_atoms must be an integer") from exc
    if not 1 <= max_atoms <= 64:
        raise AppError(ANALYSIS_INPUT_INVALID, "max_atoms must be between 1 and 64")
    try:
        max_report = int(params.get("max_report", 20))
    except (TypeError, ValueError) as exc:
        raise AppError(ANALYSIS_INPUT_INVALID, "max_report must be an integer") from exc
    max_report = max(1, min(max_report, 200))

    if not frames:
        raise AppError(ANALYSIS_INPUT_INVALID, "environment jacobian requires at least one structure")

    baseline_recompute = recompute(list(frames))
    if baseline_recompute.atomic_values is None or baseline_recompute.row_offsets is None:
        raise AppError(
            ANALYSIS_INPUT_INVALID,
            "environment jacobian requires a descriptor with per-atom rows and verified row_offsets",
        )
    baseline_rows = np.asarray(baseline_recompute.atomic_values, dtype=np.float64)
    offsets = np.asarray(baseline_recompute.row_offsets, dtype=np.int64)
    if offsets.shape[0] != len(frames) + 1:
        raise AppError(
            ANALYSIS_INPUT_INVALID,
            "row_offsets do not cover the selected frames",
            {"frames": len(frames), "offsets": int(offsets.shape[0] - 1)},
        )

    atom_records: list[dict] = []
    structure_summaries: list[dict] = []
    total_evaluations = 0
    skipped_structures: list[int] = []

    for structure_index, frame in enumerate(frames):
        if progress:
            progress((structure_index + 1) / len(frames), "differentiating environments")
        numbers = np.asarray(frame.numbers)
        positions = np.asarray(frame.positions, dtype=np.float64)
        cell = np.asarray(frame.cell, dtype=np.float64)
        pbc = np.asarray(frame.pbc, dtype=bool)
        natoms = int(numbers.shape[0])
        start, end = int(offsets[structure_index]), int(offsets[structure_index + 1])
        if end - start != natoms:
            raise AppError(
                ANALYSIS_INPUT_INVALID,
                "atom row count does not match the structure atom count",
                {"structure": structure_index, "rows": end - start, "atoms": natoms},
            )
        # The displaced-copy buffer and the batch rows both scale with
        # natoms^2 x features; the cap keeps one request inside a bounded
        # footprint instead of letting a large cell blow up the worker.
        if natoms > max_atoms:
            skipped_structures.append(structure_index)
            continue

        # Central finite differences: for every (atom, axis) a +/- pair.  Each
        # recompute returns every atom's rows, so all central atoms share one
        # evaluation budget of 6 * natoms.
        plus_rows = np.zeros((natoms, 3, natoms, baseline_rows.shape[1]), dtype=np.float64)
        minus_rows = np.zeros_like(plus_rows)
        displaced_batch = []
        plans = []
        for j in range(natoms):
            for axis in range(3):
                step = np.zeros(3)
                step[axis] = displacement
                for sign, bucket in ((+1.0, plus_rows), (-1.0, minus_rows)):
                    moved = positions.copy()
                    moved[j] += sign * step
                    displaced_batch.append(replace_geometry(frame, positions=moved))
                    plans.append((j, axis, sign, bucket))
        recomputed = recompute(displaced_batch)
        atomic = np.asarray(recomputed.atomic_values, dtype=np.float64)
        per_structure = natoms * 6
        if atomic.shape[0] != per_structure * natoms:
            raise AppError(
                ANALYSIS_INPUT_INVALID,
                "displaced recompute did not return one row per atom per copy",
                {"expected": per_structure * natoms, "actual": int(atomic.shape[0])},
            )
        total_evaluations += per_structure
        for copy_index, (j, axis, sign, bucket) in enumerate(plans):
            copy_offset = copy_index * natoms
            bucket[j, axis] = atomic[copy_offset : copy_offset + natoms]

        # Minimum-image neighbor spheres (exact for orthorhombic cells).
        deltas = positions[:, None, :] - positions[None, :, :]
        if pbc.any() and np.any(np.abs(cell) > 1e-12):
            inverse = np.linalg.inv(cell)
            wrap = np.where(pbc, np.round(deltas @ inverse), 0.0)
            deltas = deltas - wrap @ cell
        distances = np.linalg.norm(deltas, axis=2)

        structure_deficiency = 0
        structure_atoms = 0
        for center in range(natoms):
            neighbors = np.flatnonzero((distances[center] <= cutoff) & (np.arange(natoms) != center))
            base_row = baseline_rows[start + center]
            if neighbors.size == 0:
                atom_records.append(
                    {
                        "structure_index": structure_index,
                        "atom_index": center,
                        "species": int(numbers[center]),
                        "neighbor_count": 0,
                        "effective_neighbor_count": 0,
                        "expected_rank": 0,
                        "observed_rank": 0,
                        "rank_deficiency": 0,
                        "sigma_max": 0.0,
                        "sigma_min_significant": None,
                        "condition_number": None,
                        "rotational_residual": None,
                        "verdict": "isolated",
                    }
                )
                structure_atoms += 1
                continue
            jacobian = np.empty((neighbors.size * 3, base_row.size), dtype=np.float64)
            for slot, j in enumerate(neighbors):
                for axis in range(3):
                    jacobian[slot * 3 + axis] = (plus_rows[j, axis, center] - minus_rows[j, axis, center]) / (2.0 * displacement)
            stats = _analyze_environment(jacobian, deltas[center, neighbors], rank_tolerance)
            # Neighbors the descriptor actually sees: a column of the Jacobian
            # that never responds cannot contribute rank, and a gap between
            # this count and neighbor_count usually means the analysis cutoff
            # exceeds the descriptor's own cutoff.
            column_norms = np.linalg.norm(jacobian, axis=1)
            responsive = column_norms > 1e-12 * max(float(np.max(column_norms)), 1e-300)
            effective = int(np.count_nonzero(responsive)) // 3
            stats["effective_neighbor_count"] = effective
            verdict = "ok" if stats["rank_deficiency"] <= 0 else "deficient"
            atom_records.append(
                {
                    "structure_index": structure_index,
                    "atom_index": center,
                    "species": int(numbers[center]),
                    "verdict": verdict,
                    **stats,
                }
            )
            structure_atoms += 1
            structure_deficiency += max(stats["rank_deficiency"], 0)

        structure_summaries.append(
            {
                "structure_index": structure_index,
                "atoms_analyzed": structure_atoms,
                "total_rank_deficiency": structure_deficiency,
                "evaluations": per_structure,
            }
        )

    deficient = [record for record in atom_records if record.get("rank_deficiency", 0) > 0]
    deficient.sort(key=lambda record: (-record["rank_deficiency"], -(record.get("condition_number") or 0.0)))
    residuals = [
        record["rotational_residual"]
        for record in atom_records
        if record.get("rotational_residual") is not None
    ]
    max_rotational_residual = max(residuals) if residuals else None
    cutoff_hints = sum(
        1
        for record in deficient
        if record.get("effective_neighbor_count", 0) < record.get("neighbor_count", 0)
    )
    warnings: list[str] = []
    if skipped_structures:
        warnings.append(
            f"skipped {len(skipped_structures)} structure(s) with more than max_atoms={max_atoms} atoms: {skipped_structures[:10]}"
        )
    if cutoff_hints:
        warnings.append(
            f"{cutoff_hints} deficient environment(s) have unresponsive neighbors: "
            "check that the analysis cutoff matches the descriptor's own cutoff before reading this as incompleteness"
        )
    rotational_failures = [
        record
        for record in atom_records
        if record.get("rotational_residual") is not None and record["rotational_residual"] > 1e-4
    ]
    if rotational_failures:
        warnings.append(
            f"{len(rotational_failures)} environment(s) show a first-order rotational response: "
            "the descriptor may not be rotation-invariant to numerical precision"
        )
    return {
        "arrays": {
            "rank_deficiency": np.asarray([record.get("rank_deficiency", 0) for record in atom_records], dtype=np.int64),
            "expected_rank": np.asarray([record.get("expected_rank", 0) for record in atom_records], dtype=np.int64),
            "observed_rank": np.asarray([record.get("observed_rank", 0) for record in atom_records], dtype=np.int64),
            "neighbor_count": np.asarray([record.get("neighbor_count", 0) for record in atom_records], dtype=np.int64),
        },
        "preview": {
            "kind": "environment_jacobian",
            "cutoff": cutoff,
            "displacement": displacement,
            "rank_tolerance": rank_tolerance,
            "structures": structure_summaries,
            "atoms_analyzed": len(atom_records),
            "n_deficient": len(deficient),
            "max_rotational_residual": max_rotational_residual,
            "total_descriptor_evaluations": total_evaluations + max(len(frames) - len(skipped_structures), 0),
            "skipped_structures": skipped_structures,
            "max_atoms": max_atoms,
            "worst_atoms": deficient[:max_report],
            "isolated_atoms": sum(1 for record in atom_records if record.get("verdict") == "isolated"),
        },
        "warnings": warnings,
    }
